# monorepo only work when using virtual manifest
# see: https://github.com/rust-lang/cargo/issues/7467#issuecomment-867632379
[workspace]
members = [
    "packages/app",
    "packages/web",
    "packages/worker",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
