[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.2.4", features = ["ssr"] }
dioxus-free-icons = { version = "0.3.1", features = ["font-awesome-brands", "font-awesome-solid"] }

[profile.release]
lto = true
opt-level = 's'
