name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install Denoflare
        run:
          deno install --unstable --allow-read --allow-net --allow-env --allow-run --name denoflare --force \
          https://raw.githubusercontent.com/skymethod/denoflare/fd922e410602d7c0950f8af014365d196e8cabb2/cli/cli.ts
      - name: Deploy
        run: deno task publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
